### ISSUE TITLE
Backend: E-Mailkonfiguration

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#1]
Die Mails mit Grußkarten sollen an ausgewählte LIsten an Mailadressen gesendet werden.
Als Absender ist aus Gründen der Sicherheit jedoch nicht der WordPress-Server-Account oder die Mailadresse der WP-Instanz zu nutzen.
Stattdessen soll ein Mail-Account in der Konfiguration angegeben werden, zusammen mit Hostnamen des Mailservers, PWD etc.

Mails sollen nur über diesen Account versendet werden.

Solange kein Account in der Konfiguration angegeen ist, kann auch keine Mail versendet werden.

**Comment by xwolfde** [comment]
Siehe auch #2 zu Mailkonfiguration

**Comment by rvdforst** [comment]
Erledigt. Es ist nur erlaubt, E-Mails über einen externen Mailserver (SMTP) zu senden.
