### ISSUE TITLE
Rollenmanagement

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#10]
Die Funktionen des Plugins sollen ab der Redaktionsrolle nutzbar sein

**Comment by rvdforst** [comment]
Administratoren können Grußkarten erstellen und auch senden. Darüber hinaus gibt es die benutzerdefinierte Rolle "Greeting Agent", die die Capabilities der Redaktionsrolle und die Capabilities zum Verwalten der Grußkarten enthält.
