### ISSUE TITLE
Backend: Sendung timen / Statusanzeige

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#11]
Eine Aussendung soll mit einem Start-Zeitpunkt versehen werden können ab der die Mails automatisch ausgesendet werden.
Somit soll eine manuelle Sendung #4 unnötig werden.

Als Eingabe soll (nur) Datum+Zeit eingegeben werden. Zunächst keine wiederholbaren Termine.

Bei großen Maillisten, die erwartungsgemäß aufgrund der Rate-limits #2 nicht sofort alle Mails aussenden können, soll eine Statusinformation ausgegeben werden, wie lange die Aussendung dauert und ggf. auch ein "Done"-Status anzeigbar gemacht werden.

**Comment by rvdforst** [comment]
Ist erledigt.
Statusanzeige einer Grußkarte:
- Sende (send) - Die Grußkarte ist bereit zum Senden, wurde jedoch noch nicht an die Queue gesendet. In diesem Status kann die Sendung manuell abgebrochen werden.
- In Queue (queued) - Die Sendung wurde in die Queue gestellt. In diesem Status ist es nicht möglich, die Sendung abzubrechen.
- Gesendet (sent) Die Queue wurde bereits erstellt und kann die E-Mails zum voreingestellten Datum senden.
