### ISSUE TITLE
Umsetzungsidee: Post Type Greeting

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#12]
Für die Umsetzung eines Grußes gemäß #4 folgender Lösungsansatz:

* Es wird ein Custom Post Type gemacht ("greeting").
* Titel der Mail ist auch der Titel des CPT
* Das Grußbild ist das Artikelbild
* Der Text, welcher über das Artikelbild gelegt wird, wird im Excerpt-Field gespeichert
* Der Text unterhalb des Bildes wird im Content gespeichert 

Die Verknüpfung mit der Adressliste gemäß #3 erfolgt mit einem Custom Post Field.

Vorteile: 
+ Wir können die WP Funktionen nutzen
+ Wir haben eine feste URL für die Online-Darstellung des Grußes auf die wir verlinken können

**Comment by rvdforst** [comment]
Ist erledigt.

**Comment by rvdforst** [comment]
So wurde es in Version 1.0.0-alpha umgesetzt:
- CPT 'greeting': Erstellung un Verwaltung der Grußkarten
- Der Titel des CPT (post_title) ist auch der Betreff der Grußkarte-E-Mail
- Das Bild der Grußkarte ist das Artikelbild
- Die HTML-Version der Grußkarte wird im Beitragsinhalt (post_content) gespeichert
- Die Plain-Text-Version der Grußkarte wird im Beitrags-Excerpt (post_excerpt) gespeichert
