### ISSUE TITLE
Backend: Mailtemplates

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#13]
Bei der Sendung der Mails sollte ein oder mehrere Mailtemplates zur Auswahl möglich sein.

Dies kann bei der Erstellung der Meldung als CPT in #12 über ein dort auswählbares Template gewählt werden.

Ein Template besteht bei der Umsetzung/Anzeige jedoch in Wirklichkeit aus 2 Templates, die bei der Sendung der E-Mail verwendet werden:
* HTML-Form der E-Mail
* Text-Form der E-Mail

**Comment by rvdforst** [comment]
Vorschlag: 
- Implementierung eines CPT (greeting_template) zur Erstellung und Verwaltung von Mailtemplates.

Auf diese Weise können Administratoren oder "Greetings Agents" ihre eigenen Vorlagen erstellen und die entsprechenden CFs hinzufügen.
Für die Erstellung von Metaboxen wird CMB2 verwendet.

UPDATE: Ist erledigt!
