### ISSUE TITLE
Backend: E-Mailkonfiguration - Cron-Einstellungen und Rate-Limits

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#2]
Werden Mails an Listen von Adressen gesendet, ist sicherzustellen, dass keine Rate-Limits des Mailrelays überschritten werden.
Daher soll per Default dafür Sorge getragen werden, dass bei dem Versandt an viele Hundert Mailadressen nicht mehr als 15 Mails pro Minute  gesendet werden.
Hierzu sind entsprechende Queues für das Cron einzustellen.

Anforderung Postmaster:

> Eingeliefert wird per smtp.uni-erlangen.de, Limit von 250 Recips/SMTP-Transaktion und 450
> Recips/15m. Einlieferndes Tool muss mit temporaeren Ablehnungen sinnvoll umgehen koennen (Requeuing).

**Comment by rvdforst** [comment]
Erledigt. Die jeweiligen Limits können unter Einstellungen / Grußkarten konfiguriert werden.
