### ISSUE TITLE
Backend: Erstellen einer Sendung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#4]
Eine Versendung von Grußkarten-Mails besteht aus:
1.  Titel der Mail
2. Liste der Adressaten (nur E-Mailadressen, ohne Vornamen, Nachnamen, Anreden, etc). Die Liste der Adressaten wird aus einer vordefinierten Adressgruppe genommen. Diese Gruppe wird gesondert bearbeitet und enthält dann E-Mailadressen. Vgl. #5 
3. Grafik, die aus der Mediathek ausgewählt wird, die ggf. aber zusätzliche Parameter hat. Vgl. #6 und #7 
4. Kurzer Text für eine Montierung (Bearbeitung!) an vorgegebener Stelle in der Grafik; ggf. mit eingeschränkter Auswahl an Schriftart und Schriftfarbe. SIehe hierzu Issue #6 
5. Text, der bei dem erzeugten Mailing danach unter der Grafik angezeigt werden soll

**Comment by rvdforst** [comment]
Ist erledigt.
