### ISSUE TITLE
Backend: Erstellen einer Adressatengruppe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#5]
Zur Erstellung einer Sendung sollen zuvor Adressaten erstellt werden, die Gruppen zugeordnet sind.
Die Gruppe besteht aus einem Titel/Namen (Z.B. "Weihnachtskartenempfänger" oder "Empfänger Geheimprojekte Beta") udn einer Liste an Mailadressen. Die Liste an Mailadressen wird nicht einzeln eingegeben sondern in einem Textfeld in der pro Zeile eine Mailadresse ist.
Die Mailadressen werden nur nach Validität geprüft.
Eine Mailadresse kann gleichzeitig in mehreren Gruppen sein. In einer Gruppe soll sie aber jeweils nur einmal vorkommen.

**Comment by rvdforst** [comment]
Erledigt.  Zur Verwaltung der Mailinglisten wurde eine Taxonomie verwendet.
