### ISSUE TITLE
Backend:  Grafiken für Sendung bearbeiten und zur Verfügung stellen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#6]
Die Grafiken sollen mit der Mediathek hochgeladen werden.
Zusätzlich muss es aber zu jeder Grafik zusätzliche Parameter geben können:

* x- und y-Koordinaten für das Einfügen einer Textgrafik
* Default-Größe für einen einzufügenden Text 
* Max. Anzahl der Buchstaben für den einzufügenden Text
* Auswahl an nutzbaren Schriftfonts (diese müssen dann natürlich auch bei der Erstellung der Grafik in der verwendeten LIbrary vorhanden sein!)

**Comment by rvdforst** [comment]
Ist erledigt.
