### ISSUE TITLE
Erstellung von Grafiken zur Aussendung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-greetings#7]
Zur Erstellung einer Sendung soll die Möglichkeit bestehen eine neue Grafik zu erstellen.
Hierzu wird eine Grafik aus der Liste, die via #6 verwaltet wird, ausgewählt.
Wenn nun ein Text in die Grafik montiert wird, wird so mit einer geeigneten Grafik-Bib eine neue Grafik erstellt.
Diese neue Grafik soll auch im System unter einer öffentlich erreichbaren URL erreichbar sein.

Sie muss aber nicht in der Medienthek auftauchen und könnte alternativ auch on the fly beim Aufruf neu erstellt werden.

Auf die URL wird in der Mail verwiesen für solche Fälle in denen man keine HTML-Mails lesen kann.

**Comment by rvdforst** [comment]
Das verarbeitete Bild wird in der Medienbibliothek unter dem Namen greeting-card-{random-ID} gespeichert. Das verarbeitete Bild wird jedoch nicht in der Medienbibliothek angezeigt.

**Comment by rvdforst** [comment]
Erledigt.
